### PR TITLE
Notes for Neuroconductor

### PR DESCRIPTION
**Pull request by muschellij2**
Added continuous integration to the repo to see if the package checks out, here are the builds:
https://travis-ci.com/muschellij2/NDTr/builds

It looks like there are some errors and warnings.  

A few notes:
1. The repo size is quite substantial - over 500mb when cloned.
2. A lot of packages are straight imported, and Hadley recommendation from http://r-pkgs.had.co.nz/namespace.html is:
> Alternatively, if you are repeatedly using many functions from another package, you can import all of them using @import package. This is the least recommended solution because it makes your code harder to read (you can’t tell where a function is coming from), and if you @import many packages, it increases the chance of conflicting function names.
3.  Please see http://r-pkgs.had.co.nz/data.html for including data in a package.  The `data/` folder shouldn't have sub-folders.  Any non Rda files (e.g. the `.mat` files) should not be in the `data/` folder.
4. Some vignettes seem to be duplicated or were Rmd files, not really vignettes. 

I'd recommend using the `usethis` package.  I also have some notes here: https://johnmuschelli.com/neuroc/getting_ready_for_submission/index.html

### CODE REVIEW

**Comment by muschellij2** [comment]
@adigherman @ccrainic

**Comment by emeyers** [comment]
Hi John,

I am finally getting close to finishing my neural decoding package and
wanted to check with you to see if there are any changes I should make to
make it compatible with Neuroconductor. I am planning on submitting my
package to CRAN by the end of the summer after making just a few more
changes (e.g., I am likely to chance the package name to NeuroDecodeR) so
if you could let me know of any other changes I should make before I submit
to CRAN I would appreciate it.

Thanks,
Ethan

**Comment by adigherman** [comment]
Ethan,

I submitted your package to the development site to see how it behaves and it passed our required tests. Logs can be found [here](https://travis-ci.com/github/neuroconductor-devel/NDTr/builds/181556193). The failing tests are for R 3.4 but it's expected as you require R >= 3.5. 

Please go ahead and submit to Neuroconductor (https://neuroconductor.org/submit-package)

Best,
Adi

@muschellij2

**Comment by emeyers** [comment]
Thanks Adi!  I renamed the package NeuroDecodeR and made a few more small
changes. I will submit it to Neuroconductor soon.

Ethan

**Pull request merged**
